import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { withServerSideAuth } from '@clerk/nextjs/ssr';
import { useState } from 'react';
export default function Home({ catFacts }) {
  const [fact, setFact] = useState(catFacts.fact);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{fact}</h1>
        <button
          onClick={async () => {
            const request = await fetch('/api/getFacts');
            const results = await request.json();
            setFact(results.fact);
          }}
          className={styles.button}
        >
          Get a fact
        </button>
      </main>
    </div>
  );
}

export const getServerSideProps = withServerSideAuth(
  async ({ req, resolvedUrl }) => {
    const { sessionId } = req.auth;

    if (!sessionId) {
      return {
        redirect: { destination: '/sign-in?redirect_url=' + resolvedUrl }
      };
    }
    const request = await fetch('https://catfact.ninja/fact');
    const catFacts = await request.json();
    return {
      props: {
        catFacts
      }
    };
  }
);
